server:
  web:
    host: 0.0.0.0
    port: 3000
  websocket:
    host: localhost
    port: 1337
  dist:
    web: web
    config: config
client:
  id: 0
  secret: secret
slug:
  lower: true
  replacement: _
global:
  hostname: localhost
  dist: dist
